### ISSUE TITLE
Linked filters not working

### ISSUE THREAD

**Issue by shughes111** [koalyptus/TableFilter#141]
Hi

First let me congratulate you on a great tool!
I am using the latest version of TableFilter and an trying to use linked filters, however the filters do not appear to exhibit the linked properties:

   var filtersConfig = {
        base_path: 'tablefilter/',
linked_filters: true,
refresh_filters: true, 
disable_excluded_options: true,
        grid_layout: true, .........}

Am I missing something basic here? (I am using IE10/Edge)

**Comment by koalyptus** [comment]
Hi @shughes111,
From what I see there seem to be an issue on the click event, filters are linked.
Tagging this as a bug.
Cheers

**Comment by koalyptus** [comment]
@shughes111,
IE issue with linked filters feature should be now fixed in v0.1.18.
Tell me how it goes.

BTW, you can remove the `refresh_filters: true,` option, this was the option name in the HTML Table Filter Generator plugin.

**Comment by shughes111** [comment]
Hi there! I have downloaded the new build, and copied the contents of the dist folder to my site (only using the default theme under the /themes folder) but still the linked filters is not working. Are there other files I should upload?

**Comment by koalyptus** [comment]
Make sure you got the right version, the build is placed in expected location in your folder structure and check this demo out to see it working: http://koalyptus.github.io/TableFilter/linked-filters.html with IE/edge.
Cheers

**Comment by shughes111** [comment]
I can see that working fine, and I have downloaded version 0.1.18 but still no joy. Is it just the tablefilter folder under /dist I need to have in my site build, and does it matter if I only load the default theme and not the others?

**Comment by koalyptus** [comment]
Yes it's all in the dist folder and you don't need all the theme folders if you use the default one.
What do you mean by 'no joy' exactly? I need more context, a description of the issue, of javascript errors if any etc.

**Comment by koalyptus** [comment]
Ok I think I found the issue... the linked filter does not refresh when `grid_layout` is on. I just saw the `grid_layout` setting in your configuration.
Keeping this issue open until it is fixed.
Cheers

**Comment by koalyptus** [comment]
Just pushed v0.1.19, it should now work with `grid_layout` turned on.
Give it a try.

**Comment by shughes111** [comment]
Just downloaded the latest version and applied to site. Not sure if it is our webservers but now the grid presentation takes 2-3 minutes to load and once I click a filter dropdown and select a value nothing happens even after 10 minutes (just have the Microsoft spinner)... I have also tried on another PC with another internet connection (>100M dedicated line) and still the same issue. The table is 1700 records long but previous version was quite fast.

**Comment by koalyptus** [comment]
Try to turn off the disable_excluded_options option as it has a known performance issue regardless the version. Now when you say 'previous version was quite fast', which version and was the exact same configuration? Do you mean it was previously working in grid layout mode with linked filters and disable_excluded_options?

**Comment by shughes111** [comment]
Previous version I refer to was 0.1.15 but that was the version with linked filter not working. 
However..... version 0.1.19 used in site, nested filters working!!! Removed disable_excluded_options and performance is much much faster. 
Thanks for all your help!!!!

**Comment by koalyptus** [comment]
Cool closing this one then,
cheers

**Comment by shughes111** [comment]
Thanks for all your help!

Quoting koalyptus <notifications@github.com>:

> Cool closing this one then,
> cheers
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/koalyptus/TableFilter/issues/141#issuecomment-195890479


--
